import {StyleSheet, Platform} from 'react-native';

const cardShadow = Platform.select({
  ios: {
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: {width: 0, height: 6},
  },
  android: {elevation: 3},
});

export default StyleSheet.create({
  safe: {flex: 1, backgroundColor: '#fff'},
  container: {flex: 1, padding: 12, paddingBottom: 110},

  header: {fontSize: 20, fontWeight: '900', color: '#111827', marginBottom: 8},

  metaCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 12,
    marginBottom: 12,
    ...cardShadow,
  },
  metaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 4,
  },
  metaLabel: {color: '#6B7280', fontSize: 13},
  metaValue: {color: '#111827', fontSize: 13, fontWeight: '800'},
  addrLabel: {marginTop: 8, color: '#6B7280', fontSize: 13},
  addrValue: {marginTop: 4, color: '#111827', fontSize: 13, fontWeight: '700'},
  divider: {height: 1, backgroundColor: '#E5E7EB'},

  stepperWrap: {marginTop: 6, marginBottom: 6, paddingHorizontal: 6},
  track: {
    position: 'absolute',
    left: 20,
    right: 20,
    top: 18,
    height: 4,
    backgroundColor: '#E5E7EB',
    borderRadius: 4,
  },
  trackFill: {
    position: 'absolute',
    left: 20,
    top: 18,
    height: 4,
    backgroundColor: '#2563EB',
    borderRadius: 4,
  },
  circlesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    alignItems: 'center',
  },
  circleWrap: {alignItems: 'center', width: 72},
  circle: {
    width: 28,
    height: 28,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: '#9CA3AF',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    ...cardShadow,
  },
  check: {color: '#fff', fontWeight: '900'},
  stepLabel: {marginTop: 6, textAlign: 'center', fontSize: 11},
  stepLabelMuted: {color: '#9CA3AF', fontWeight: '600'},
  stepLabelDone: {color: '#111827', fontWeight: '800'},

  card: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 12,
    marginTop: 8,
    ...cardShadow,
  },
  section: {fontSize: 15, fontWeight: '800', color: '#111827', marginBottom: 6},

  timelineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 8,
  },
  dot: {width: 10, height: 10, borderRadius: 10},
  timelineTitle: {color: '#6B7280', fontSize: 13, fontWeight: '700'},
  timelineTime: {color: '#9CA3AF', fontSize: 12, marginTop: 2},
  statusPill: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#ECFDF5',
    color: '#065F46',
    fontWeight: '800',
    fontSize: 11,
  },
  sep: {height: 1, backgroundColor: '#F3F4F6'},

  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    padding: 12,
    backgroundColor: '#fff',
    flexDirection: 'row',
    gap: 12,
    ...cardShadow,
  },
  btn: {
    flex: 1,
    height: 50,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primary: {backgroundColor: '#111827'},
  primaryTxt: {color: '#fff', fontWeight: '800', fontSize: 16},
  ghost: {backgroundColor: '#E5E7EB'},
  ghostTxt: {color: '#111827', fontWeight: '800', fontSize: 16},
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCard: {
    width: '78%',
    backgroundColor: '#fff',
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#111827',
    marginBottom: 8,
  },
  modalPhone: {
    fontSize: 18,
    fontWeight: '900',
    color: '#2563EB',
    letterSpacing: 0.2,
    marginBottom: 16,
  },
  modalCloseBtn: {
    marginTop: 4,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: '#111827',
  },
  modalCloseTxt: {
    color: '#fff',
    fontWeight: '800',
  },
});
